/**************************************************************************************
Exclusion of Liability for this demo software:
  The following software is intended for and must only be used for reference and in an
  evaluation laboratory environment. It is provided without charge and is subject to
  alterations. There is no warranty for the software, to the extent permitted by
  applicable law. Except when otherwise stated in writing the copyright holders and/or
  other parties provide the software "as is" without warranty of any kind, either
  expressed or implied.
  Please refer to the Agreement in README_DISCLAIMER.txt, provided together with this file!
  By installing or otherwise using the software, you accept the terms of this Agreement.
  If you do not agree to the terms of this Agreement, then do not install or use the
  Software!
**************************************************************************************/

/**************************************************************************************

Copyright (c) Hilscher Gesellschaft fuer Systemautomation mbH. All Rights Reserved.

***************************************************************************************/

#ifndef COMPONENTS_CIFXAPPLICATIONDEMODNS_INCLUDES_APPDNS_DEMOAPPLICATION_H_
#define COMPONENTS_CIFXAPPLICATIONDEMODNS_INCLUDES_APPDNS_DEMOAPPLICATION_H_

#include <stdio.h>
#include <string.h>

/* Generic example application framework includes */
#include "App_DemoApplication.h"
#include "App_PacketCommunication.h"
#include "App_SystemPackets.h"

/* LFW Packet API: Hilscher specific CIP codes */
#include "HIL_ProductCodeCip.h"

/* DeviceNet Includes*/
#include "DNS_includes.h"


/*************************************************************************************/
typedef struct APP_DNS_DATA_Ttag
{
  uint8_t bNodeIdValue;
  uint8_t bBaudRateValue;
} APP_DNS_DATA_T;


#define TX_TIMEOUT       5000 /* milliseconds */
#define TXRX_TIMEOUT     5000 /* milliseconds */

#define DNS_PROCESS_DATA_INPUT_SIZE             6
#define DNS_PROCESS_DATA_OUTPUT_SIZE            10

/*************************************************************************************/
typedef struct PROTOCOL_IDENTIFICATION_Ttag
{
  const char* szFirmwareName;
  const uint16_t usFirmwareMajor;
  const uint16_t usFirmwareMinor;
} PROTOCOL_IDENTIFICATION_T;

extern PROTOCOL_IDENTIFICATION_T g_tProtocolIdentification;


typedef struct APP_COMM_CHANNEL_HANDLER_RSC_Ttag
{
  CIFXHANDLE           hCifXChannel;
  CHANNEL_INFORMATION* ptCifXChannelInfo;

  PKT_INTERFACE_H      hPktIfRsc;
  CIFX_PACKET          tPacket;

  uint8_t abActorData[DNS_PROCESS_DATA_INPUT_SIZE];   /* Control data produced by Master, to control device peripherals (e.g. LEDs) */
  uint8_t abSensorData[DNS_PROCESS_DATA_OUTPUT_SIZE]; /* Status data for the Master, generated by the device peripherals (e.g. Temperature)*/

} APP_DNS_CHANNEL_HANDLER_RSC_T;


/*************************************************************************************/
bool     AppDNS_PacketHandler            (void* pvUserData, CIFX_PACKET* ptPacket);

uint32_t AppDNS_GlobalPacket_SendReceive (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
uint32_t AppDNS_GlobalPacket_Send        (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
void*    AppDNS_GlobalPacket_Get         (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
void*    AppDNS_GlobalPacket_Init        (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);

uint32_t AppDNS_ConfigureStack           (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc, uint32_t ulBusOnDelay);

uint32_t AppDNS_DDP_SetSerialNumber     (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
uint32_t AppDNS_DDP_Activate            (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);

void     AppDNS_StoreRemanent_Indication (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
uint32_t AppDNS_SetRemanentData          (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);

uint32_t AppDNS_ConnObject_Registration (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
void     AppDNS_ConnObject_Indication   (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc,
                                         DNS_PACKET_CIP_SERVICE_IND_T*  ptInd,
                                         DNS_PACKET_CIP_SERVICE_RES_T*  ptRes,
                                         uint32_t*                      pulResDataSize);

uint32_t AppDNS_UserObject_Registration   (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
bool     AppDNS_UserObject_IsRegistered   (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc, uint32_t ulClass, uint32_t ulInstance);
void     AppDNS_UserObject_Indication     (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc,
                                           DNS_PACKET_CIP_SERVICE_IND_T*  ptInd,
                                           DNS_PACKET_CIP_SERVICE_RES_T*  ptRes,
                                           uint32_t*                      pulResDataSize);

uint32_t AppDNS_MnsObject_Registration  (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);
void     AppDNS_MnsObject_Indication    (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc,
                                         DNS_PACKET_CIP_SERVICE_IND_T*  ptInd,
                                         DNS_PACKET_CIP_SERVICE_RES_T*  ptRes,
                                         uint32_t*                      pulResDataSize);

uint32_t AppDNS_AsObject_Registration   (APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);

uint32_t AppDNS_CipService(APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc,
                           uint32_t                       ulService,
                           uint32_t                       ulClass,
                           uint32_t                       ulInstance,
                           uint32_t                       ulAttribute,
                           uint8_t*                       pbData,
                           uint32_t                       ulSize);

void    AppDNS_SetNodeIdValue(APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc, uint8_t bNodeIdSwitchValue);
uint8_t AppDNS_GetNodeIdValue(APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);

void    AppDNS_SetBaudRateValue(APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc, uint8_t bBaudSwitchValue);
uint8_t AppDNS_GetBaudRateValue(APP_DNS_CHANNEL_HANDLER_RSC_T* ptDnsRsc);


#endif /* COMPONENTS_CIFXAPPLICATIONDEMODNS_INCLUDES_APPDNS_DEMOAPPLICATION_H_ */
