/**************************************************************************************
Exclusion of Liability for this demo software:
  The following software is intended for and must only be used for reference and in an
  evaluation laboratory environment. It is provided without charge and is subject to
  alterations. There is no warranty for the software, to the extent permitted by
  applicable law. Except when otherwise stated in writing the copyright holders and/or
  other parties provide the software "as is" without warranty of any kind, either
  expressed or implied.
  Please refer to the Agreement in README_DISCLAIMER.txt, provided together with this file!
  By installing or otherwise using the software, you accept the terms of this Agreement.
  If you do not agree to the terms of this Agreement, then do not install or use the
  Software!
**************************************************************************************/

/**************************************************************************************

Copyright (c) Hilscher Gesellschaft fuer Systemautomation mbH. All Rights Reserved.

***************************************************************************************/

#ifndef COMPONENTS_CIFXAPPLICATIONDEMOEIS_INCLUDES_APPEIS_DEMOAPPLICATION_H_
#define COMPONENTS_CIFXAPPLICATIONDEMOEIS_INCLUDES_APPEIS_DEMOAPPLICATION_H_

#include "App_DemoApplication.h"

/* DNS Includes*/
#include "DNS_includes.h"

/***************************************************************************************/

#define DNS_DEMO_CHANNEL_INDEX  0

#define DNS_PROCESS_DATA_INPUT_SIZE             6
#define DNS_PROCESS_DATA_OUTPUT_SIZE            10

/*************************************************************************************/
/* Forward declarations and type definitions */
/*************************************************************************************/
/* Handle to the packet handler */
typedef struct PKT_INTERFACE_Ttag *PKT_INTERFACE_H;

/*************************************************************************************/
/*************************************************************************************/


/*************************************************************************************/
/*************************************************************************************/
typedef struct APP_DNS_DATA_Ttag
{
  uint8_t bNodeIdValue;
  uint8_t bBaudRateValue;
} APP_DNS_DATA_T;

/*************************************************************************************/
/* Channel Handler Resource Structure */
/*************************************************************************************/
typedef struct APP_DNS_CHANNEL_HANDLER_RSC_Ttag
{
  CIFXHANDLE           hCifXChannel;
  CHANNEL_INFORMATION* ptCifXChannelInfo;

  PKT_INTERFACE_H      hPktIfRsc;
  CIFX_PACKET          tPacket;

  uint8_t abActorData[DNS_PROCESS_DATA_INPUT_SIZE];   /* Control data produced by Master, to control device peripherals (e.g. LEDs) */
  uint8_t abSensorData[DNS_PROCESS_DATA_OUTPUT_SIZE]; /* Status data for the Master, generated by the device peripherals (e.g. Temperature)*/

} APP_DNS_CHANNEL_HANDLER_RSC_T;

/*************************************************************************************/
/*************************************************************************************/
/*************************************************************************************/

bool     AppDNS_PacketHandler_callback   ( CIFX_PACKET* ptPacket, void* pvUserData );

uint32_t AppDNS_GlobalPacket_SendReceive ( APP_DATA_T* ptAppData );
uint32_t AppDNS_GlobalPacket_Send        ( APP_DATA_T* ptAppData);
void*    AppDNS_GlobalPacket_Get         ( APP_DATA_T* ptAppData);
void*    AppDNS_GlobalPacket_Init        ( APP_DATA_T* ptAppData );

uint32_t AppDNS_ConfigureStack            ( APP_DATA_T* ptAppData, uint32_t ulBusOnDelay);
uint32_t AppDNS_RegisterAllVatClasses     ( APP_DATA_T* ptAppData );
void     AppDNS_HandleCipServiceIndication( APP_DATA_T* ptAppData );


#endif /* COMPONENTS_CIFXAPPLICATIONDEMOEIS_INCLUDES_APPEIS_DEMOAPPLICATION_H_ */
