def build(bld):
    
    toolchain = bld.env["UsedToolchain"]
    if not toolchain:
        bld.fatal('Environment parameter "UsedToolchain" is not available! Make sure to provide the environment parameter "UsedToolchain" in the root wscript file of your project. e.g.: conf.env["UsedToolchain"] = "gccarmemb"')
    
    platform  = bld.env["UsedPlatform"]
    if not platform:
        bld.fatal('Environment parameter "UsedPlatform" is not available! Make sure to provide the environment parameter "UsedPlatform" in the root wscript file of your project. e.g.: conf.env["UsedPlatform"]  = "netx90_app"')
    
    comp_prefix = bld.get_name_prefix(
        toolchain = toolchain,
        platform  = platform)
    
    sources = [
        "Source/handler.c",
        "Source/main.c",
        "Source/netx90_app_header.c",
    ]
    
    includes = [
        "Include",
    ]
    
    defines = [ 
        "__NETX90",
        "_NETX_",
        ]
    
    uses = [ 
        comp_prefix + "CMSIS",
        comp_prefix + "netx_drv"
        ]
    
    bld.program(
        target           = "netx90_app_intram",
        name             = comp_prefix + "netx90_app_intram",
        platform         = platform,
        toolchain        = toolchain,
        use              = uses,
        source           = sources,
        includes         = includes,
        defines          = defines,
        linkerscript     = ["Linker/netx90_app_intram.ld"],
    )
    
    bld.program(
        target           = "netx90_app_sdram",
        name             = comp_prefix + "netx90_app_sdram",
        platform         = platform,
        toolchain        = toolchain,
        use              = uses,
        source           = sources,
        includes         = includes,
        defines          = defines,
        linkerscript     = ["Linker/netx90_app_sdram.ld"],
    )
    
    bld.program(
        target           = "netx90_app_iflash",
        name             = comp_prefix + "netx90_app_iflash",
        platform         = platform,
        toolchain        = toolchain,
        use              = uses,
        source           = sources,
        includes         = includes,
        defines          = defines,
        linkerscript     = ["Linker/netx90_app_iflash.ld"],
    )
    
    bld.generate_netx90_intflash2_image(
        target           = "netx90_app_iflash.nai",
        use              = comp_prefix + "netx90_app_iflash"
    )
    
    bld.sdkcomponent(
        name             = "cmsis_configuration_sdk",
        export_defines   = [
                           "__STACK_SIZE = 0x00002000",
                           "__HEAP_SIZE =  0x00008000",
                           ],
    )
    
    bld.sdkcomponent(
        name             = "netx_drv_configuration_sdk",
        export_includes  = includes,
    )    
    
    